global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
# connect to AlertManager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - 'alertmanager:9093'

# include alert rules (to be used by AlertManager)
rule_files:
  - '/etc/prometheus/security.yaml'
# alerting:
#   alertmanagers:
#   - static_configs:
#     - targets: []
#     scheme: http
#     timeout: 10s
#     api_version: v1
scrape_configs:
  - job_name: prometheus
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: chain-mon
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - balance-mon:7300
          - fault-mon-op:7301
          - initialized-upgraded-mon-op:7302
          - wallet-mon-op:7304
          - wd-mon-op:7303
          - fault-mon-base:7305
          - initialized-upgraded-mon-base:7306
          - wallet-mon-base:7308
          - wd-mon-base:7307
