groups:
  - name: fault-detector
    rules:
      - alert: fault-detector-stalled-seal
        expr: sum by(cluster, namespace, job) (increase(fault_detector_highest_output_index[6h])) < 1
        for: 1h
        annotations:
          summary: Fault Detector Stalled ({{ toUpper ( reReplaceAll "-" " " (reReplaceAll "fault-detector/pod-monitor-" "" $labels.job)) }})
          runbook_url: https://www.notion.so/oplabs/RB-106-Alert-Fault-Detector-Mismatch-4fe028618437440b85766d23a90120b6
        labels:
          team: security
          severity: P2
      # TODO(https://github.com/ethereum-optimism/security-pod/issues/84): Replace with dispute-mon alerts once dispute-mon is productionized.
      # - alert: fault-detector-stalled-op-sepolia
      #   expr: sum by(cluster, namespace, job) (increase(fault_detector_highest_output_index{cluster="oplabs-prod-sepolia-primary", namespace="fault-detector", job=~"fault-detector.*-op-sepolia.*"}[6h])) < 1
      #   for: 1h
      #   annotations:
      #     summary: Fault Detector Stalled (OP Sepolia)
      #     runbook_url: https://www.notion.so/oplabs/RB-106-Alert-Fault-Detector-Mismatch-4fe028618437440b85766d23a90120b6
      #   labels:
      #     team: security
      #     severity: P3
      - alert: fault-detector-error-unhandled-seal
        expr: fault_detector_unhandled_errors > 0
        for: 10m
        annotations:
          summary: Unhandled Errors in Fault Detector ({{ toUpper ( reReplaceAll "-" " " (reReplaceAll "fault-detector/pod-monitor-" "" $labels.job)) }})
          runbook_url: https://www.notion.so/oplabs/RB-106-Alert-Fault-Detector-Mismatch-4fe028618437440b85766d23a90120b6
        labels:
          team: security
          severity: P2
      # TODO(https://github.com/ethereum-optimism/security-pod/issues/84): Replace with dispute-mon alerts once dispute-mon is productionized.
      # - alert: fault-detector-error-unhandled-op-sepolia
      #   expr: fault_detector_unhandled_errors{cluster="oplabs-prod-sepolia-primary", namespace="fault-detector", job=~"fault-detector.*-op-sepolia.*"} > 0
      #   for: 10m
      #   annotations:
      #     summary: Unhandled Errors in Fault Detector (OP Sepolia)
      #     runbook_url: https://www.notion.so/oplabs/RB-106-Alert-Fault-Detector-Mismatch-4fe028618437440b85766d23a90120b6
      #   labels:
      #     team: security
      #     severity: P3
      - alert: fault-detector-mismatch-detected-seal
        expr: fault_detector_is_currently_mismatched > 0
        for: 2m
        annotations:
          summary: Output Root Mismatch Detected in Fault Detector ({{ toUpper ( reReplaceAll "-" " " (reReplaceAll "fault-detector/pod-monitor-" "" $labels.job)) }})
          runbook_url: https://www.notion.so/oplabs/RB-106-Alert-Fault-Detector-Mismatch-4fe028618437440b85766d23a90120b6
        labels:
          team: security
          severity: P1
      # TODO(https://github.com/ethereum-optimism/security-pod/issues/84): Replace with dispute-mon alerts once dispute-mon is productionized.
      # - alert: fault-detector-mismatch-detected-op-sepolia
      #   expr: fault_detector_is_currently_mismatched{cluster="oplabs-prod-sepolia-primary", namespace="fault-detector", job=~"fault-detector.*-op-sepolia.*"} > 0
      #   for: 2m
      #   annotations:
      #     summary: Output Root Mismatch Detected in Fault Detector (OP Sepolia)
      #     runbook_url: https://www.notion.so/oplabs/RB-106-Alert-Fault-Detector-Mismatch-4fe028618437440b85766d23a90120b6
      #   labels:
      #     team: security
      #     severity: P2
  - name: wd-mon
    rules:
      - alert: two-step-withdraw-forgery-detection-stalled-seal
        expr: sum by(cluster, namespace, job) (increase(two_step_monitor_withdrawals_validated[24h])) < 1
        for: 1h
        annotations:
          summary: Two Step Withdraw Forgery Detection Stalled ({{ toUpper ( reReplaceAll "-" " " (reReplaceAll "wd-mon/pod-monitor-" "" $labels.job)) }})
          runbook_url: https://www.notion.so/oplabs/RB-107-Alert-Two-Step-Withdraw-Forgery-Detected-62fb1ba454274dc78bd719eb762fd6ae
        labels:
          team: security
          severity: P2
      # TODO(https://github.com/ethereum-optimism/security-pod/issues/84): Re-enable once wd-mon is updated to the latest version that supports Fault Proof contracts.
      # - alert: two-step-withdraw-forgery-detection-stalled-sepolia
      #   expr: sum by(cluster, namespace, job) (increase(two_step_monitor_withdrawals_validated{cluster="oplabs-prod-sepolia-primary", namespace="wd-mon", job=~".*op-sepolia.*"}[96h])) < 1
      #   for: 1h
      #   annotations:
      #     summary: Two Step Withdraw Forgery Detection Stalled (Sepolia)
      #     runbook_url: https://www.notion.so/oplabs/RB-107-Alert-Two-Step-Withdraw-Forgery-Detected-62fb1ba454274dc78bd719eb762fd6ae
      #   labels:
      #     team: security
      #     severity: P3
      - alert: two-step-withdraw-forgery-detection-error-unhandled-seal
        expr: increase(two_step_monitor_unhandled_errors[24h]) > 0
        for: 10m
        annotations:
          summary: Unhandled Errors in Two Step Withdraw Forgery Detection ({{ toUpper ( reReplaceAll "-" " " (reReplaceAll "wd-mon/pod-monitor-" "" $labels.job)) }})
          runbook_url: https://www.notion.so/oplabs/RB-107-Alert-Two-Step-Withdraw-Forgery-Detected-62fb1ba454274dc78bd719eb762fd6ae
        labels:
          team: security
          severity: P2
      # TODO(https://github.com/ethereum-optimism/security-pod/issues/84): Re-enable once wd-mon is updated to the latest version that supports Fault Proof contracts.
      # - alert: two-step-withdraw-forgery-detection-error-unhandled-sepolia
      #   expr: increase(two_step_monitor_unhandled_errors{cluster="oplabs-prod-sepolia-primary", namespace="wd-mon", job=~".*op-sepolia.*"}[24h]) > 0
      #   for: 10m
      #   annotations:
      #     summary: Unhandled Errors in Two Step Withdraw Forgery Detection (Sepolia)
      #     runbook_url: https://www.notion.so/oplabs/RB-107-Alert-Two-Step-Withdraw-Forgery-Detected-62fb1ba454274dc78bd719eb762fd6ae
      #   labels:
      #     team: security
      #     severity: P3
      - alert: two-step-withdraw-forgery-detected-seal
        expr: two_step_monitor_is_detecting_forgeries > 0
        for: 2m
        annotations:
          summary: Forgery detected in Two Step Withdraws (({{ toUpper ( reReplaceAll "-" " " (reReplaceAll "wd-mon/pod-monitor-" "" $labels.job)) }}))
          runbook_url: https://www.notion.so/oplabs/RB-107-Alert-Two-Step-Withdraw-Forgery-Detected-62fb1ba454274dc78bd719eb762fd6ae
        labels:
          team: security
          severity: P1
      # TODO(https://github.com/ethereum-optimism/security-pod/issues/84): Re-enable once wd-mon is updated to the latest version that supports Fault Proof contracts.
      # - alert: two-step-withdraw-forgery-detected-sepolia
      #   expr: two_step_monitor_is_detecting_forgeries{cluster="oplabs-prod-sepolia-primary", namespace="wd-mon", job=~".*op-sepolia.*"} > 0
      #   for: 2m
      #   annotations:
      #     summary: Forgery detected in Two Step Withdraws (Sepolia)
      #     runbook_url: https://www.notion.so/oplabs/RB-107-Alert-Two-Step-Withdraw-Forgery-Detected-62fb1ba454274dc78bd719eb762fd6ae
      #   labels:
      #     team: security
      #     severity: P2
  - name: balance-mon
    # rules evaluation period
    interval: 1s
    rules:
      # balance monitor metrics simple rule
      - alert: balance-mon-has-balance-seal
        # balance monitor has balance
        expr: balance_mon_balances > 0
        # during 10 seconds
        for: 10s
        labels:
          severity: P3
        annotations:
          summary: "Balance monitor has balance"
          runbook_url: https://securityalliance.org

