groups:
  - name: fault-detector
    rules:
      - alert: fault-detector-stalled-seal
        expr: sum by(cluster, namespace, job) (increase(fault_detector_highest_output_index[6h])) < 1
        for: 1h
        annotations:
          summary: Fault Detector Stalled ({{ toUpper ( reReplaceAll "-" " " (reReplaceAll "fault-detector/pod-monitor-" "" $labels.job)) }})
        labels:
          team: security
          severity: P2
      - alert: fault-detector-error-unhandled-seal
        expr: fault_detector_unhandled_errors > 0
        for: 10m
        annotations:
          summary: Unhandled Errors in Fault Detector ({{ toUpper ( reReplaceAll "-" " " (reReplaceAll "fault-detector/pod-monitor-" "" $labels.job)) }})
        labels:
          team: security
          severity: P2
      - alert: fault-detector-mismatch-detected-seal
        expr: fault_detector_is_currently_mismatched > 0
        for: 2m
        annotations:
          summary: Output Root Mismatch Detected in Fault Detector ({{ toUpper ( reReplaceAll "-" " " (reReplaceAll "fault-detector/pod-monitor-" "" $labels.job)) }})
        labels:
          team: security
          severity: P1
  - name: wd-mon
    rules:
      - alert: two-step-withdraw-forgery-detection-stalled-seal
        expr: sum by(cluster, namespace, job) (increase(two_step_monitor_withdrawals_validated[24h])) < 1
        for: 1h
        annotations:
          summary: Two Step Withdraw Forgery Detection Stalled ({{ toUpper ( reReplaceAll "-" " " (reReplaceAll "wd-mon/pod-monitor-" "" $labels.job)) }})
        labels:
          team: security
          severity: P2
      - alert: two-step-withdraw-forgery-detection-error-unhandled-seal
        expr: increase(two_step_monitor_unhandled_errors[24h]) > 0
        for: 10m
        annotations:
          summary: Unhandled Errors in Two Step Withdraw Forgery Detection ({{ toUpper ( reReplaceAll "-" " " (reReplaceAll "wd-mon/pod-monitor-" "" $labels.job)) }})
        labels:
          team: security
          severity: P2
      - alert: two-step-withdraw-forgery-detected-seal
        expr: two_step_monitor_is_detecting_forgeries > 0
        for: 2m
        annotations:
          summary: Forgery detected in Two Step Withdraws (({{ toUpper ( reReplaceAll "-" " " (reReplaceAll "wd-mon/pod-monitor-" "" $labels.job)) }}))
        labels:
          team: security
          severity: P1
  - name: balance-mon
    # rules evaluation period
    interval: 1s
    rules:
      # balance monitor metrics simple rule
      - alert: balance-mon-has-balance-seal
        # balance monitor has balance
        expr: balance_mon_balances > 0
        # during 10 seconds
        for: 10s
        labels:
          severity: P3
        annotations:
          summary: "Balance monitor has balance"

